### ISSUE TITLE
Valencian is not Catalan

### ISSUE THREAD

**Issue by delafuente** [datagica/languages#2]
I hope no valencian or catalan guy has found this already, or you are in danger:

description": "Catalan",
  "aliases": {
    "en": ["Catalan", "Valencian"],
    "fr": ["catalan", "valencien"]
  },

Valencian is a dialect of Catalan language, not a synonym. If you are listing languages and also dialects, perhaps this could be a new single entry, but it's wrong as it is now.

**Comment by jbilcke** [comment]
Hi @delafuente,

I agree with you, I will put Valencian in its own entry.

The reason for this error is that I used data from ISO-639 tables, but unfortunately the current ISO-639 standard is wrong about Valencian and indeed merged it with Catalan.

However, there have been efforts to add Valencian to ISO-639: http://www-01.sil.org/iso639-3/cr_files/2006-129_vac.pdf

After some digging, I found out that the mistake is in Wikipedia as well:
- https://en.wiktionary.org/wiki/Valencian says "`An alternate name for the Catalan language, recognized by ISO 639.`" which we can now agree is a poor definition!

**Comment by jbilcke** [comment]
Made the change:

 https://github.com/datagica/languages/blob/master/data/all-languages.json#L4650

**Comment by delafuente** [comment]
Hi, @jbilcke,

There should be a misconception mixing the language and the dialect, perhaps it's really used as an alternate name for Catalan outside Spain, but I think the best approach is to have them separated if you are showing languages and dialects, or showing only Catalan for a 'language only' approach, but never mixing them. Even more, you could name Valencian as Catalan, but not the other way.

I think this fix is perfect. Thanks
